https://www.perplexity.ai/search/qing-jie-shao-yi-xia-shi-mo-sh-xCoAz67VSsiwWdIunaamJA

In [5]:
import numpy as np
np.random.random()
np.random.random(3)
np.random.random(size=3)
np.random.random((3, 4))

array([[0.55659902, 0.20671851, 0.44920852, 0.87313602],
       [0.55702675, 0.25243224, 0.3061106 , 0.45246992],
       [0.18149421, 0.39285896, 0.83371299, 0.98017969]])

In [20]:
from numpy.random import normal

normal_value = normal(size=(3, 4))
#ndarray常用的實體屬性
type(normal_value)
normal_value.ndim
normal_value.size
normal_value.shape
normal_value.dtype
normal_value

array([[ 2.04461343, -0.09986231,  0.95095897,  0.61222089],
       [-0.20933302,  0.05585367, -0.15875755,  1.12488236],
       [ 0.21758031, -0.38717292, -1.69605667,  0.33698586]])

In [21]:
#ndarray,陣列運算
normal_value * 10

array([[ 20.44613425,  -0.99862307,   9.50958968,   6.12220894],
       [ -2.09333019,   0.55853667,  -1.58757553,  11.24882359],
       [  2.17580312,  -3.87172922, -16.96056666,   3.3698586 ]])

In [18]:
#ndarray,的統計
normal_value.sum()
normal_value.sum(axis=0)
normal_value.sum(axis=1)


array([-0.11130178, -0.37041814,  2.59166673])