https://www.perplexity.ai/search/pythonwei-he-yao-shi-yong-nump-Sji8SG7fRaKbUKCu0DAJgw

In [5]:
scores:list = [10, 20, 30, 40, 50]
scores:list = list(range(10,60,10))
scores1:list = list()
for score in scores:
    score += 5
    print (score)

15
25
35
45
55


In [11]:
scores:list = [10, 20, 30, 40, 50]
scores:list = list(range(10,60,10))

#scores1:list = list()
#for score in scores:
#    score += 5
#    scores1.append(score)
scores1 =[score+5 for score in scores]
scores1


[15, 25, 35, 45, 55]

https://numpy.org/doc/stable/reference/generated/numpy.array.html

In [ ]:
#numpy
import numpy as np

array=np.array([10, 20, 30, 40, 50])
type(array)
array1 = array + 5
array1

array([15, 25, 35, 45, 55])

In [7]:
import numpy as np
from numpy import ndarray

students: ndarray = np.array([
    [78, 92, 68, 95, 91],
    [65, 75, 63, 84, 86]
])

print(students)


[[78 92 68 95 91]
 [65 75 63 84 86]]


In [ ]:
import numpy as np
from numpy import ndarray

students:ndarray = np.array([78, 92, 68, 95, 91],
                        [65, 75, 63, 84, 86])
#索引(index),切割(slice)
students


TypeError: Field elements must be 2- or 3-tuples, got '65'